inherit_from: .rubocop_todo.yml

# inherit_from: .rubocop_todo.yml

Layout/IndentationWidth:
  Width: 4

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false
